### ISSUE TITLE
Hi, I need mod support for JustEnoughCharacters

### ISSUE THREAD

**Issue by shengcaixing** [AE2-UEL/Applied-Energistics-2#119]
Hi, I need mod support for JustEnoughCharacters, it is available in JEI but not on this branch, please join in
  
Here's the information
MOD:appliedenergistics2-rv6-stable-7-extended_life-v0.52.8
MOD:JustEnoughCharacters-1.12.0-3.5.1

package:Nomifactory (dev branch, c0562a7)

**Comment by KuroPeach** [comment]
Just replace HadEnoughItems with JEI，will work

**Comment by vfyjxf** [comment]
Please update your jech, i've uploaded a fix version.
