### ISSUE TITLE
Add some extra blocks 

### ISSUE THREAD

**Issue by subr72** [AE2-UEL/Applied-Energistics-2#136]
Add some blocks. 

**Describe the feature**

1. Add "compressed" creation processing blocks.  It will be very convenient to replace hundreds of creation processing units with just a couple blocks!  Since there are no addons that add such a thing, alas, it would be cool if this was implemented.  2. ME cable with a large number of channels, for example "Main ME cable" which will not have 32 channels, but for example, 64-128.  It will be very convenient to build with the "GregTech" mod, since 1 wire will replace 2-4 pilot ME cables.
**Reasons why it should be considered**
Very convenient, optimization.

**Additional Context**
As an example, you can use this addon for "AE2 1.7.10" 
https://www.curseforge.com/minecraft/mc-mods/ae2-additions

Thank you for your time on this topic, I hope it will be implemented, because everything that is not done is for the better!  😁

**Comment by WALHAY** [comment]
All these freatures are already added in my PAE2 fork for my modpack.
But there is no crafting recipe for all these items, so you will have to add craftings manually
Here the link https://github.com/GregTech-Precision/Applied-Energistics-2-Precision-Edition/releases/tag/multi-thread_co-processors

**Comment by YiRanMushroom** [comment]
hey, can you update your fork to the newest version? 
cuz many problem&bugs have already been fixed in 0.54 
maybe you could wait for the beta/release version?

**Comment by serenibyss** [comment]
This is part of NAE2
