### ISSUE TITLE
Add missing items compatability with JEI

### ISSUE THREAD

**Issue by Nevrai** [AE2-UEL/Applied-Energistics-2#139]
### Describe the feature

[JEI](https://www.curseforge.com/minecraft/mc-mods/jei) highlights the items you’re missing for a craft when crafting in any crafting table, but this does not work in an AE2 crafting terminal or wireless crafting terminal. It should be possible to implement this, as this is a functionality of [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage), even including highlighting items in blue if the items are missing but are craftable via pattern auto-crafting.

Here’s what it looks like in a crafting table:

![awsfShI](https://user-images.githubusercontent.com/59761487/189542583-72097f9c-fc28-41a1-ae8c-94a1ffefeed2.png)

Personally, not having highlighting on missing items in JEI with the crafting terminal and wireless crafting terminal makes using them pretty difficult, especially when being accustomed to that functionality in Refined Storage, and it makes it especially difficult when crafting items with many parts.

Is this something you could implement into AE2 Unofficial Extended Life? It’s my most wanted feature for sure, and I’ve seen many others also befuddled that this isn’t a feature of AE2.

### Reasons why it should be considered

Being able to see what items you’re missing in red highlighting when mousing over the plus button, and even what items you’re missing but are auto-craftable in blue highlighting (which would be fantastic, but even just the red highlighting on missing items would be a blessing) would make crafting items in crafting terminals far more convenient and less tedious, especially when crafting items involving a lot of different items in their recipes.

**Comment by NotMyWing** [comment]
This feature exists now, so I'm closing this as completed.
