### ISSUE TITLE
Engineering Processor can't be made in the Advanced Inscriber?

### ISSUE THREAD

**Issue by Handeril** [AE2-UEL/Applied-Energistics-2#143]
**Describe the bug**
You can't make Engineering Processors in the Advanced Inscriber with this fork installed, yet it works in the main version (I'm pretty sure.) The reason I'm making the bug report here and not on the mod's issue tracker is because it's been 5 years since AEStuff received an update, and it appears to be an issue with the fork (since I don't recall the original AE2 mod having this issue with AE2 Stuff).

**To Reproduce**
Install AE2 Unofficial Extended Life's latest version, appliedenergistics2-rv6-stable-7-extended_life-v0.53.7b.jar
Install AE2 Stuff's latest version, ae2stuff-0.7.0.4-mc1.12.2.jar
Start up a singleplayer world.
Power up an ME Controller in Creative.
Put the Advanced Inscriber next to it.
Put your Engineering Press in
Then realize the Diamonds won't budge from your inventory.

**Expected behavior**
Should be able to make Engineering Processors in the Advanced Inscriber - works for the others just fine...

**Additional context**
[Twitch Clip Video](https://clips.twitch.tv/AliveFastParrotPeanutButterJellyTime-5FiZkfngnZBMwlQI)
Apologies for me getting distracted with the Chaos Nodes for a moment - I swear I'm not streaming from my toaster. lol

**Environment**
Seems like you're pretty sure you want all the details. Oh boy, here we go...

I've seen this bug in Singleplayer so far, but it might occur in Multiplayer too.

Here's that list of all mods you asked for - have fun:
![image](https://user-images.githubusercontent.com/83894721/190887666-69877fae-c901-4ece-a81d-eb0e888bcf8e.png)
![image](https://user-images.githubusercontent.com/83894721/190887653-91928cd9-ff0e-4891-82b8-5870308fe788.png)

- Minecraft Version: 

appliedenergistics2-rv6-stable-7-extended_life-v0.52.8.jar (I did update and try this on the latest version, appliedenergistics2-rv6-stable-7-extended_life-v0.53.7b.jar, this bug still exists.)

forge-14.23.5.2860

ae2stuff-0.7.0.4-mc1.12.2.jar

**Comment by Handeril** [comment]
This issue also effects trying to make normal processors in the Advanced Inscriber. I just attempted that, and found out today.

**Comment by serenibyss** [comment]
This would be an issue for AE2 Stuff Unofficial, though I'm unable to reproduce it on latest
