### ISSUE TITLE
Security Terminal GUI messed up with JEI

### ISSUE THREAD

**Issue by WaitingIdly** [AE2-UEL/Applied-Energistics-2#148]
**Describe the bug**
Security Terminal GUI sidebars are downshifted due to the recent JEI exclusion areas.

**To Reproduce**
Load up the latest version of AE2-EL

**Expected behavior**
Align the GUI and item icon correctly, as before. 

**Additional context**

With JEI:
![Screenshot_23-2](https://user-images.githubusercontent.com/25394029/191941118-7b0de583-c9f9-4c18-922f-d3f99e2ca6fa.png)

Without JEI installed:
![Screenshot_23-3](https://user-images.githubusercontent.com/25394029/191941345-bae413f1-81ff-45cd-93eb-df801ad1031a.png)

**Environment**
- AE2 Version: v0.53.7b, and reproducible in the latest commit (90112732292ebe68b57f110b336ccce3d8e5c4aa)

**Comment by serenibyss** [comment]
Not able to reproduce on latest
