### ISSUE TITLE
Ctrl + Click [+]

### ISSUE THREAD

**Issue by XeramHosting** [AE2-UEL/Applied-Energistics-2#155]
**Describe the feature**

In Refined Storage users have the ability to press Ctrl + [+] in JEI and then be presented with the option to start crafting the items from that recipe that they already have a pattern for.

**Reasons why it should be considered**

This feature makes it so that players don't need a pattern for every single item, and if they don't have everything in stock in their system they can request it more easily versus having to either make a pattern for the final result or going in and finding each item they need individually.

**Additional Context**

I can't provide screenshots at the moment, but I can try to give an example of this feature in action.

In this scenario I want to create a chest, but do not have any planks in my system. I also don't have a pattern for a chest but I do have a pattern for making planks from logs. If while looking at the chest recipe (8 planks) I press Ctrl + [+] in JEI I will be given the option to start a craft for 8 planks.

I apologize in advance if this is something that's already been requested and denied, or if it's a feature and I'm just an idiot who isn't doing it correctly.

**Comment by YoungOnionMC** [comment]
So basically request missing items feature..... 😐

**Comment by XeramHosting** [comment]
Your response is throwing me off a bit, and this may just be me overthinking. To my understanding, the missing items "feature" is where JEI tells/shows you that a certain item isn't available in an inventory, but it also doesn't let you craft it.

Like this: 
![image](https://user-images.githubusercontent.com/28981899/196005828-3d4e32d8-73c0-4d70-8564-03a7cf2966ae.png)

While if you do it in a terminal it doesn't give you that notice, nor does it prevent you from attempting the craft.

Like this:
![image](https://user-images.githubusercontent.com/28981899/196005862-cf083e93-27fc-47e1-83e1-88a605b2baa9.png)

What I was suggesting would be somewhere in the middle. Using the same example above about the chest.

![image](https://user-images.githubusercontent.com/28981899/196006213-e2fef625-8ad5-4890-8ec1-67ef167e86b7.png)
As you can see, my system has 64 logs, a planks pattern, but no chest pattern.

![image](https://user-images.githubusercontent.com/28981899/196006240-b4410a37-5934-4cd2-90c3-a09ae8a3b4cd.png)
If I were to try and craft a chest, the system alerts me that I don't have enough items (Missing Items Feature?) However, it knows I can autocraft planks and highlights them blue to indicate as much. For my suggestion, that's the important part.

In this system, if I were to click the + no items would be added to the crafting section, because I do not have those readily available. AE2 does the same thing. Where it differs, and where my suggestion begins, is if I hold Ctrl and press +. 
![image](https://user-images.githubusercontent.com/28981899/196006305-07e4c6d9-bfd4-4a40-a1ee-604ec1e5a169.png)
As you can see, in RS doing that combo opens up the option for me to craft those missing items that I already have patterns for. This is not a possibility in AE2, at least not that I can tell.


I'm very sorry if this is what you meant by your message, I wasn't 100% sure. I did see someone request the missing items notice in an earlier request, but they just glossed over the auto crafting functionality. I don't necessarily need the system to tell me an item is missing, or even have it prevent me from pressing + if some parts of a recipe are missing, I'd simply like the ability to start a craft of missing items without having to create a pattern for the "main" recipe, if that makes sense.

**Comment by vfyjxf** [comment]
You can try [Not Enough Energistics](https://www.curseforge.com/minecraft/mc-mods/not-enough-energistics).

**Comment by serenibyss** [comment]
This is part of NAE2 currently, and will be moved to AE2UEL natively in the near future
