### ISSUE TITLE
ME Controller colors not synchronized

### ISSUE THREAD

**Issue by mcailac** [AE2-UEL/Applied-Energistics-2#162]
**Describe the bug**

Colors of ME controller are not synchronized in corners of the structure.

**To Reproduce**

Create a ME controller structure in square for example and observe the colors not synchronized.

**Expected behavior**

Colors should be synchronized with the rest of the structure.

**Additional context**

![image](https://user-images.githubusercontent.com/32125458/196984607-454fb0c6-92c4-4ae4-8ac6-ad7f3490a016.png)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.53.3
- Forge Version: Forge - 14.23.5.2860
- ModPack: Dinine_Journey_2.16.0

I think I found the issue but not 100% sure.
To me, `frames` array in .mcmeta files should be exactly the same if we want to use color in same order. Array of [controller_column_lights.png.mcmeta](https://github.com/PrototypeTrousers/Applied-Energistics-2/blob/AE2-Omnifactory/src/main/resources/assets/appliedenergistics2/textures/blocks/controller_column_lights.png.mcmeta) begins with `1`, while the one of [controller_lights.png.mcmeta](https://github.com/PrototypeTrousers/Applied-Energistics-2/blob/AE2-Omnifactory/src/main/resources/assets/appliedenergistics2/textures/blocks/controller_lights.png.mcmeta) begins with `0`.

Sadly, I don't have the knowledge to test if it really fix the issue. But I'm pretty sure it's linked.

**Comment by serenibyss** [comment]
This is fixed as part of #338
