### ISSUE TITLE
Can ultra dense cable be ported from GTNewHorizons version of AE2 ?

### ISSUE THREAD

**Issue by Manuepolis23** [AE2-UEL/Applied-Energistics-2#169]
Can ultra dense cable be ported from GTNewHorizons  version of AE2?

I think these are the necessary changes: 
- https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/89
- https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/122

**Comment by PrototypeTrousers** [comment]
Why would someone even need this? We dont have GT:NH on 1.12.2

**Comment by Manuepolis23** [comment]
Yes but would be a nice addition for AE2

**Comment by yang-fu** [comment]
I also think it is necessary. Although 1.12.2 does not have gtnh, but GTCEu.

**Comment by serenibyss** [comment]
These have since been removed from GTNH AE2 due to them being unnecessary and having many issues: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/367, so I don't think bringing them to 1.12 is a good idea
