### ISSUE TITLE
Disassemble the crafting storage

### ISSUE THREAD

**Issue by RuiXuqi** [AE2-UEL/Applied-Energistics-2#215]
Shift and right click to disassemble the crafting storages on hand to turn them into storage componenst and crafting units, just like disks.
Thank you!

**Comment by IntegerLimit** [comment]
Put it into a crafting grid by itself. It will turn into Crafting Unit + Storage Component.

**Comment by NotMyWing** [comment]
This is a native AE2 feature that already exists!
