### ISSUE TITLE
ore dict storage bus crush game

### ISSUE THREAD

**Issue by CoBa31Rus** [AE2-UEL/Applied-Energistics-2#237]
**Describe the bug**
when i configure ore dict storage bus priority, game crush (log1), after that first load world is crush (log2), bus is removed from the world with me cable. Some time when i configure ore dict like ingotHot* or similar bus tries to store all incoming stuff respecting the priority (pic). I don't know how to repeat it because it's random. Logs from v54.19

**Additional context**

![2023-03-06 22_51_12-Minecraft 1 12 2](https://user-images.githubusercontent.com/25090318/223391916-d8234db9-8846-4e86-b08e-a29e8dc97a98.png)

[log1.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10908247/log1.log)
[log2.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10908249/log2.log)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: 54.19, 54.8, 54.9
- Forge Version: 2860

**Comment by CoBa31Rus** [comment]
Perhaps I will add logs from 55.9.
[log1.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10908645/log1.log)

**Comment by CoBa31Rus** [comment]
I found an incompatible mod. Oredict doesn't work with it. Perhaps the reason is in the library.
[Mod](https://www.curseforge.com/minecraft/mc-mods/trash-cans)
[Lib](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)

**Comment by NotMyWing** [comment]
Cannot reproduce on v0.55.29. Used mods:
* SuperMartijn642's Core Lib 1.1.16a 
* Trash Cans 1.0.18

The error seems to be originating from our code, but I'm afraid I couldn't find any reason for a NullPointerException to be thrown. Please let me know if this is still a problem, and I'll reopen the issue.
