### ISSUE TITLE
New cell models from v0.54.8+ break the ME Chest rendering into an X-ray

### ISSUE THREAD

**Issue by Purple-Towel** [AE2-UEL/Applied-Energistics-2#245]
#### Description
The rendering of ME Chests breaks the face that accesses the contents of the storage cell inside of it, which then renders the terminal face as an x-ray.

![Screenshot of Bugged ME Chest](https://user-images.githubusercontent.com/8131582/226277587-d6985574-cbb9-42da-97ed-ead112ceac40.png)
This is an example of the visual bug

Curiously, from #227 it seems that the model for the ME Chest is working fine in the screenshots submitted by @RuiXuqi, so I have no clue if this is an issue that seems to be only affecting my setup.

#### Environment
Just a very barebones setup of AE2UEL, and JEI was used to creat the screenshot, no other mods.
- Minecraft Version: 1.12.2
- AE2 Version: v0.55.10
- Forge Version: 14.23.5.2860

**Comment by Purple-Towel** [comment]
Update:
After rolling back to v0.55.8 and still getting the issue with the broken rendering, I then dig around deeper and have reason to believe that this rendering issue goes back to #166 when the 1.18+ models were backported by @Xikaro

Now, rolling versions _that_ far back in my personal modpack or reverting cosmetic changes back to baseline AE2 1.12.2 for just an audience of 1 person is probably unrealistic, so either way this is going to be a difficult problem. I have 0 clue what could be causing this but since every other screenshot of the newer models seems to be working fine I don't mind if this is marked closed without a solution, and I suppose _if_ I'm desparate enough I **could just** fork this fork and revert those changes while maintaining the other QoL stuff myself.

**Comment by Xikaro** [comment]
it seems that this is observed only with you and may be a conflict with another mod
![Screenshot_58](https://user-images.githubusercontent.com/55663835/226305686-56e85a14-aa6e-4b79-8ea8-1b0cb9157502.png)

**Comment by Xikaro** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/55663835/226314209-deac93a7-a155-4137-ae4a-d89f9f6ac0b6.png)

**Comment by Xikaro** [comment]
I fixed it already, I'll open the PR right now

**Comment by serenibyss** [comment]
Fixed by #246
