### ISSUE TITLE
this feature idea

### ISSUE THREAD

**Issue by Dawsondude2023** [AE2-UEL/Applied-Energistics-2#267]
**Describe the feature**
customize the channels on cable

**Reasons why it should be considered**
< I don't have a reason for the idea just excellent idea that i like in gtnh being  able to have dense cable holding 128 channels basically idea is having option to customize the channels on cable . another reason give more customize for pack makers too  even give challenge with ae2 more custom feeling instead of having default channels and disable channels

**Comment by serenibyss** [comment]
This is already a feature, can go up to 256
