### ISSUE TITLE
suggestion to add more coprocessors

### ISSUE THREAD

**Issue by KiraLinux** [AE2-UEL/Applied-Energistics-2#279]
add coprocessors so that there are more operations in one block, 8, 16, 32, 64, 128, 256 operations in one block

this will bypass the size limit of the multi-block structure

this allows the autocrafting of the ME network to work as quickly as possible with a huge number of mechanisms

**Comment by NotMyWing** [comment]
We're not really looking forward into adding larger coprocessors into AE2 natively. You can, however, install [NAE2](https://github.com/AE2-UEL/NAE2) which has them.
