### ISSUE TITLE
Meteor Compass Target change

### ISSUE THREAD

**Issue by ThePansmith** [AE2-UEL/Applied-Energistics-2#284]
**Describe the feature**
Changing the meteor compass' target from skyblock blocks to skystone chests.

**Reasons why it should be considered**
It would eliminate the issue of having the clear out every single skystone block in a chunk so that the compass would not target it. Rather, one would just have to break the chest.

**Comment by brachy84** [comment]
To further improve this we can give skystones chests a nbt tag when placed by a player so it wont get targeted by compasses
