### ISSUE TITLE
View Cells don't apply until inventory is updated

### ISSUE THREAD

**Issue by brisingraerowing** [AE2-UEL/Applied-Energistics-2#297]
**Describe the bug**

View cells do not apply to any terminal until the inventory grid in the terminal is updated by adding or removing an item. This occurs every time a terminal is opened.

**To Reproduce**

Encode a view cell with some items
Put it into a terminal
Observe that nothing changes
Click an item
Filtering applies

**Expected behavior**

Filtering applies when the View Cell is inserted and when a Terminal with a View Cell is opened.

**Additional context**
View Cell:
![2023-08-05_17 54 36](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/250409/43c52998-f2e2-4127-9e86-5f3333790da1)

Terminal upon view cell insertion / Opening with an inserted view cell:
![2023-08-05_17 54 48](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/250409/5a23ff4c-e41d-4f7c-b97f-10147bd25580)

Terminal upon inventory update:
![2023-08-05_17 54 52](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/250409/cb29f892-52e1-4012-ae05-67089cd67749)

**Environment**
Singleplayer

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7-extended_life-v0.55.20
- Forge Version: 14.23.5.2860

**Comment by NotMyWing** [comment]
Cannot reproduce on v0.55.29, filtering applies correctly when a View Cell is inserted, with or without upgrades. Please let me know if this is still a problem, and I'll reopen the issue.
