### ISSUE TITLE
[Request] 5x5, 7x7, 9x9 (Auto)crafting

### ISSUE THREAD

**Issue by Kuzibaba** [AE2-UEL/Applied-Energistics-2#301]
**Describe the feature**
 
Adding larger crafting terminals, larger patterns and molecular assemblers.
For example, adding "Extreme Crafting Terminal" and "Extreme Pattern" which has 9x9 capacity, and "Extreme Molecular Assembler" which has 9x9 grid.

**Reasons why it should be considered**

A lot of people (including me) loves playing expert mode packs. And later in the game you get some pretty nasty craftings. Managing big craft like that all inside the me system would be awesome! Plus, I (an induvidual which is obsessed with automation) would really be glad if I could automate NxN crafts. Basically this would be a gamechanger.

**Additional Context**

RefinedAvaritia is refined storage version of my request without the terminals

(Edit: Terminals)

**Comment by CactusCool** [comment]
you can add ae2fc which adds a 6x7 pattern grid with up to 8 outputs using the ultimate encoder block.

**Comment by serenibyss** [comment]
There is also packagedauto, which can accomplish this
