### ISSUE TITLE
[Request] Bigger Crafting Co-Processors

### ISSUE THREAD

**Issue by Kuzibaba** [AE2-UEL/Applied-Energistics-2#303]
Adding 4x, 16x, 64x crafting coproccessors
**Describe the feature**

I dont think this needs further explanation
**Reasons why it should be considered**

Big crafting cores with less volume
**Additional Context**

The mod [AE2-Additions](https://legacy.curseforge.com/minecraft/mc-mods/ae2-additions) for 1.18 has a feature like this

**Comment by Kuzibaba** [comment]
Oh, hi #279

**Comment by NotMyWing** [comment]
We're not really looking forward into adding larger coprocessors into AE2 natively. You can, however, install [NAE2](https://github.com/AE2-UEL/NAE2) which has them.
