### ISSUE TITLE
Autocraft intermediates for table crafted item causing error.

### ISSUE THREAD

**Issue by Silvernova115** [AE2-UEL/Applied-Energistics-2#304]
Using v55.21 of the mod. Bug causes an error to pop up in the server in E2E-Extended modpack

**To Reproduce**
Have an auto crafting chain already in place. search JEI recipie and Ctrl+click to request items in the recipe to be crafted. the crafting computer window to initiate the request does not show up and this error pops up.

**Expected behavior**
option to initiate auto crafting intermediate ingredients.

**Additional context**
Error does not cause a crash. but prevents intended feature.
https://gist.github.com/Silvernova115/2ecf8f6d2bd40c3899204733ddeb7ff3

**Environment**
Added mod is HBM Nuclear Tech extended v1.9.8

- Minecraft Version: 1.12.2
- AE2 Version: 00.55.21
- Forge Version: 1.12.2-14.23.5.2860

**Comment by Silvernova115** [comment]
Modpack version is 1.18.0

**Comment by NotMyWing** [comment]
According to the log, the error originates from https://github.com/vfyjxf/NotEnoughEnergistics. GuiMEMonitorable is not referenced in PacketCraftingRequest on our side.
