### ISSUE TITLE
[Request] Bigger Crafting Co-Processors 1.12.2

### ISSUE THREAD

**Issue by Artiks54** [AE2-UEL/Applied-Energistics-2#307]
Hi bro you mod Good.
Please
Adding 4x, 16x, 64x 256x 512x 1024x
 crafting co-proccessors
Version Minecraft 1.12.2

**Comment by zeng-github01** [comment]
Additional mod is recommended

https://www.curseforge.com/minecraft/mc-mods/extracpus

**Comment by serenibyss** [comment]
This is implemented in NAE2: https://www.curseforge.com/minecraft/mc-mods/nae2
