### ISSUE TITLE
[Request] Add Advanced Blocking Card

### ISSUE THREAD

**Issue by MicroObsidianBlock** [AE2-UEL/Applied-Energistics-2#313]
**Describe the feature**

Make an advanced blocking card for interfaces which allows another interface block items/fluids based on the content in the system rather than that in the interface. Or just add a card that can make interface expose all content in the system, rather than only do it to a storage bus.

**Reasons why it should be considered**

Blocking mode in AE2 always has the problem of not working when using that in a multi-inport case. By enabling this can strongly simplify the automation like Assembling Line in GTCEu and the Combination Crafting in Draconic Evolution.

**Additional Context**

I posted in Glodblock's AE2-FluidCraft Rework.
https://github.com/GlodBlock/AE2FluidCraft-Rework/issues/116

The feature in GTNH:
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/308

**Comment by CactusCool** [comment]
Pae2 has this feature already built into it. Unfortunately it only works when the receiving interface is a regular interface not a dual interface so It doesn't work for ae2fc. This is an ae2fc issue not a pae2 issue.

**Comment by NotMyWing** [comment]
This is correct, the feature is already built in for items. Since AE2 doesn't support fluid crafting natively, this is more of a https://github.com/GlodBlock/AE2FluidCraft-Rework issue (specifically, https://github.com/GlodBlock/AE2FluidCraft-Rework/issues/116).
