### ISSUE TITLE
broken flux capacitor recipe every time login

### ISSUE THREAD

**Issue by akasia** [AE2-UEL/Applied-Energistics-2#36]
can i ask why that ae2 crafting flux capacitor from TE all frome leadstone to resonant whent i encode at 1st time it work well but after relog that is borken and need to encode agian to make work? 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 
- AE2 Version: v43d/v43f/v43g
- Forge Version:14.23.5.2854

**Comment by PrototypeTrousers** [comment]
have you encoded the patterns with substitutions on or off ?

**Comment by akasia** [comment]
off?

**Comment by akasia** [comment]
need to turn on?

**Comment by akasia** [comment]
i think i find out that what cos that issue happen 
my modpack has ender utilities and ender utilities has a block call junk storage for storage unstack item i has it high priority and all capacitor storage in side after it crafting at 1 state but it has issue to withdraw from junk storage i has to cancel crafting tesk and reoder crafting than it will withdraw from junk storage 
so now is this issue can be fix?

**Comment by akasia** [comment]
and evertime try crafting nonstack item hv same issue like mek machine power cube  induction cell sort stuft

**Comment by PrototypeTrousers** [comment]
sorry, i could not reproduce this issue you're having.
if you're having issues with pattern , try to encode it by placing a real item on the crafting grid (3x3), as some JEI recipes do not have the proper NBT tags when you transfer the recipe by clicking the [+] button

**Comment by NotMyWing** [comment]
I'm closing this as stale. If this still a problem, feel free to reply!
