### ISSUE TITLE
Game crash whith the 0.56.0 version, appliedintegrations compabitity problems

### ISSUE THREAD

**Issue by Robolightning** [AE2-UEL/Applied-Energistics-2#369]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Integrations (appliedintegrations)

- Minecraft Version:  1.12.2
- AE2 Version:  0.56.0
- Forge Version:  14.23.5.2860
- AppliedIntegrations Version: Beta 8.0.16.7

**Comment by serenibyss** [comment]
This mod hasn't been updated since 2020 and has no public source anymore (seems it was deleted), so there's nothing that we can do about it
