### ISSUE TITLE
The "Not Enough Energistics" function cannot be used

### ISSUE THREAD

**Issue by SenjumaruShutara** [AE2-UEL/Applied-Energistics-2#382]
AE2 Unofficial Extended Life v0.56.2;Not Enough Energistics V2.0.6
The function "Automatically switch terminal mode according to recipe" in "Not Enough Energistics" is not available, but it works normally in versions prior to "AE2 Unofficial Extended Life".

**Comment by Exaxxion** [comment]
AE2-UEL has natively supported recipe import from JEI and smart mode switching since around March 2021. NEE is not needed for these features, and may even be actively incompatible by now.

**Comment by SenjumaruShutara** [comment]
If so, in V0.56.2, this feature does not work properly

**Comment by SenjumaruShutara** [comment]
> AE2-UEL has natively supported recipe import from JEI and smart mode switching since around March 2021. NEE is not needed for these features, and may even be actively incompatible by now.

https://github.com/AE2-UEL/Applied-Energistics-2/issues/382#issuecomment-1907711929

**Comment by SenjumaruShutara** [comment]
> AE2-UEL has natively supported recipe import from JEI and smart mode switching since around March 2021. NEE is not needed for these features, and may even be actively incompatible by now.

If so, in V0.56.2, this feature does not work properly

**Comment by htmlcsjs** [comment]
do you still have nee installed?

**Comment by SenjumaruShutara** [comment]
> do you still have nee installed?

yes

**Comment by SenjumaruShutara** [comment]
> > do you still have nee installed?
> 
> yes

But not anymore

**Comment by htmlcsjs** [comment]
uninstall it, its probably breaking the native compat, and is redundant now

**Comment by SenjumaruShutara** [comment]
> uninstall it, its probably breaking the native compat, and is redundant now

After uninstallation, the related functions do not take effect
