### ISSUE TITLE
[Request]Backport from future AE2

### ISSUE THREAD

**Issue by zeng-github01** [AE2-UEL/Applied-Energistics-2#394]
**Describe the feature**
In AE2 1.19, there is a new redstone control that is unlocked ME interface when pattern output is received. Using this function, you can achieve: when one raw material gets the product, then the next one is output.

**Reasons why it should be considered**

**Additional Context**

**Comment by jakj** [comment]
You mean the way that Refined Storage blocking mode works? That would be phenomenal to have in AE, if that's the case. It's the one thing RS has over AE for automating weird stuff like magic mods.

**Comment by zeng-github01** [comment]
> You mean the way that Refined Storage blocking mode works? That would be phenomenal to have in AE, if that's the case. It's the one thing RS has over AE for automating weird stuff like magic mods.

I'm trying to implement this functionality, but I can't find the code that controls the behavior of the ME interface. And I don’t know how to draw assets, such as button icons

**Comment by zeng-github01** [comment]
There is an "isBlocking" in the interface method. I think this function can be achieved by modifying the signature of this method.@jakj

**Comment by zeng-github01** [comment]
Well, failed

**Comment by k3nw4y** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6807/commits/5807cefff38a0f25a1c48ae21e1b6f2e51336806
This is the commit and it has both assets and code

**Comment by zeng-github01** [comment]
> https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6807/commits/5807cefff38a0f25a1c48ae21e1b6f2e51336806
> This is the commit and it has both assets and code

I'm backporting exactly this commit, but it's slow and stuck.  Are there any copyright issues with this?  Should I give up? @serenibyss

**Comment by zeng-github01** [comment]
> [AppliedEnergistics@5807cef](https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/5807cefff38a0f25a1c48ae21e1b6f2e51336806) This is the commit and it has both assets and code

Thank you for the information you provided, but I found in the past that I do not have the function to transplant this change, especially for asset png, I cannot attach these two icons to the existing png.

**Comment by zeng-github01** [comment]
@k3nw4y I finally finished it, thank you for all the information
