### ISSUE TITLE
Request: Turn off extended tooltips for cells

### ISSUE THREAD

**Issue by GlennSchner** [AE2-UEL/Applied-Energistics-2#427]
**Description**
Have available in-config a method for turning off extended tooltips for cells.

**Reasons why it should be considered**
Sometimes, players may want to see the normal tooltip for a cell, as opposed to a tooltip so large it can't even fit on-screen.

![image](https://github.com/AE2-UEL/Applied-Energistics-2/assets/38408292/b1d83ba9-4675-4b84-abbb-dbf2ca055b1d)

**Comment by NotMyWing** [comment]
I do absolutely agree, something has to be done with how the tooltips are unreadable.

I'll add a config, but will also try and see if I can make the tooltips better.
