### ISSUE TITLE
Error with Thaumcraft Golems

### ISSUE THREAD

**Issue by xJon** [AE2-UEL/Applied-Energistics-2#432]
**Describe the bug**

> Thaumcraft 6 golems cant seem to place saplings using the use seal.

**To Reproduce**

> Getting this error in the server console every time the golem tries to place a sapling.

**Additional context**

https://mclo.gs/ye2pQIY

**Environment**

Started happening after updating to version `0.56.4`.

**Comment by xJon** [comment]
> the golem can place saplings after removing AE2 UEL and its dependents on server+client

**Comment by NotMyWing** [comment]
Seems like they're tripping over the latest wrench hook rewrite. I'll fix that soon.

**Comment by adma-git** [comment]
As a temporary fix for small servers, the golems can place saplings if the op list is empty
