### ISSUE TITLE
Better tooltips

### ISSUE THREAD

**Issue by RuiXuqi** [AE2-UEL/Applied-Energistics-2#435]
**Describe the feature**

Port new tooltip features back, like short energy numbers and colored texts
![IMG_20240512_204744](https://github.com/AE2-UEL/Applied-Energistics-2/assets/90179819/fb0f159c-c545-402d-b407-a13df0624389)

**Reasons why it should be considered**

**Additional Context**

**Comment by zeng-github01** [comment]
This requirement has been met. But I don't know when it will be merged

@RuiXuqi
