### ISSUE TITLE
Interface Critical BUG

### ISSUE THREAD

**Issue by Artiks54** [AE2-UEL/Applied-Energistics-2#440]
Interface Critical BUG

**Describe the bug**
The interface pushes out a different number of items depending on the side

**Expected behavior**
The interface should push the same number of items from each side.

**Additional context**
![3](https://github.com/AE2-UEL/Applied-Energistics-2/assets/145267469/08028559-bf3e-4046-b41c-e1181f64e923)
![6](https://github.com/AE2-UEL/Applied-Energistics-2/assets/145267469/eb07e23b-0e88-4a4f-b6dc-6f5165b2f228)

- Minecraft Version: 
- AE2 Version: AE2 Unofficial Extended Life − v0.56.4
- Forge Version: 14.23.5.2860

**Comment by NotMyWing** [comment]
Confirmed, looking into it.

**Comment by NotMyWing** [comment]
As a side effect of this fix, ME Interfaces are now allowed to fully utilize CPU operations to push as many items per side as CPU clusters allow (depending on the amount of co-processors), instead of doing at most 1 push per cluster cycle.
