### ISSUE TITLE
[Request] Tile advanced molecular assembler 

### ISSUE THREAD

**Issue by Artiks54** [AE2-UEL/Applied-Energistics-2#442]
**Describe the feature**
It is proposed to add an improved molecular assembler that will craft as many items per operation as there are co-processors in the system.  Or add a multiblock similar to LazzyAe2 only well optimized 

**Reasons why it should be considered**
The Lazy Ae2 mod has a lot of bugs in it and it is not optimized

**Comment by NotMyWing** [comment]
This is under consideration, but not as a mainline AE2-UEL feature. Might come to NAE2 sooner or later, https://github.com/AE2-UEL/NAE2/issues/53.
