### ISSUE TITLE
ME Interface doesn't pull items from storage

### ISSUE THREAD

**Issue by mrxdata** [AE2-UEL/Applied-Energistics-2#459]
ME Interface doesn't pull items from storage

Steps to reproduce it:
1. Place ME Storage bus
2. Place ME Interface and put any available in the ME item in the upper row of ME Interface
3. Connect it to the ME network

Items should appear and be held in the second row below set item 
I think ME Interface should pull items without storage bus at all

Video:
https://github.com/AE2-UEL/Applied-Energistics-2/assets/73149744/199c5bd1-f5c8-4875-9fb2-2f375b95eb3d

MP - CatServer

- Minecraft Version: 1.12.2
- AE2 Version: 0.56.6 
- Forge Version: 14.23.5.2860

**Comment by PedroNeto05** [comment]
I have the same issue

**Comment by NotMyWing** [comment]
Fixed in https://github.com/AE2-UEL/Applied-Energistics-2/pull/454. I'm looking forward to drop a hotfix later this day, but for now, it should be safe to rollback to v0.56.5.
