### ISSUE TITLE
Lock Crafting Broken on latest build

### ISSUE THREAD

**Issue by zeng-github01** [AE2-UEL/Applied-Energistics-2#476]
**Describe the bug**

When the lock mode is set to result lock, the production will be deadlocked, and there is no abnormality in other modes

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 
- AE2 Version:  Github Action
- Forge Version:

**Comment by zeng-github01** [comment]
@GlodBlock 应该是你最近对Me接口的输入输出修改把这个部分弄崩了。考虑修一下吗

**Comment by GlodBlock** [comment]
修了
