### ISSUE TITLE
The ME Storage Bus crashes while in use

### ISSUE THREAD

**Issue by zfms4188** [AE2-UEL/Applied-Energistics-2#485]
**Describe the bug**

When I connect any container with an ME Storage Bus, the server crashes. This issue does not occur in single-player.
**To Reproduce**

Build a normal AE network and use the bus to connect any container.
**Expected behavior**

It should not crash.
**Additional context**

 log:https://pastebin.com/3h7TvTUP
**Environment**

Server: CatServer-1.12.2-5a600445
 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.12.2/
- Minecraft Version: 1.12.2
- AE2 Version: action-ae2-uel-4528738  or v0.56.4
- Forge Version:14.23.5.2860

**Comment by KasumiNova** [comment]
给的日志怎么不完整？

**Comment by zfms4188** [comment]
> 给的日志怎么不完整？

[crash-2024-07-23_16.32.18-server.txt](https://github.com/user-attachments/files/16399081/crash-2024-07-23_16.32.18-server.txt)
太长了 只能上传文件

**Comment by KasumiNova** [comment]
你这给的是同一个日志吗？

**Comment by zfms4188** [comment]
> 你这给的是同一个日志吗？
[Uploading crash-2024-07-27_18.24.04-server.txt…]()

az。。。 这个

**Comment by zfms4188** [comment]
> 你这给的是同一个日志吗？

排查出来了,通用修复的问题。。。可恶！这东西怎么到处不兼容,还得是星核靠谱
