### ISSUE TITLE
Make shift-scrolling when holding P2Ps respect scrolling up and down

### ISSUE THREAD

**Issue by ChromaPIE** [AE2-UEL/Applied-Energistics-2#498]
Sorry for not following the template as the issue is quite simple and straightforward.
Shift-scrolling when holding P2Ps cycles through a list of type in a fixed, non-reversible order, no matter if you are scrolling up or down, and it doesn't feel right.

Now:
ME
DOWN: Redstone
DOWN: Item
UP: Fluid

Expected:
ME
DOWN: Redstone
DOWN: Item
UP: Redstone
DOWN: Item
DOWN: Fluid
UP: Item

**Comment by IntegerLimit** [comment]
This is not a feature from AE2, this is a feature from Nomi-Labs. Please close this issue and move it there instead.

**Comment by IntegerLimit** [comment]
Fixed via https://github.com/Nomi-CEu/Nomi-Labs/commit/0780a9b9342289a76722e5488f0a6227b59f2d16. Please do not open a new issue in Nomi Labs, but close this issue.

**Comment by ChromaPIE** [comment]
> Fixed via [Nomi-CEu/Nomi-Labs@0780a9b](https://github.com/Nomi-CEu/Nomi-Labs/commit/0780a9b9342289a76722e5488f0a6227b59f2d16). Please do not open a new issue in Nomi Labs, but close this issue.

OH okay much appreciation
