### ISSUE TITLE
Shiftclicking Patterns into Interface Terminal (with smart insertion)

### ISSUE THREAD

**Issue by Caedis** [AE2-UEL/Applied-Energistics-2#5]
**Describe the feature**
Shift click a pattern from the player hotbar or inventory and insert it into the top-left most interface (top-left as in the interface directly under the last one) in the interface terminal.

**Reasons why it should be considered**
An annoying part of adding many recipes to the interface terminal is the fact that you have to manually drag each one from your inventory to the correct interface. Hopefully this request fixes the mild annoyance.

**Comment by Exaxxion** [comment]
While this sounds good, it's probably a lot harder to implement than you think. Computers can carry out specific instructions based on available information, but they can't gauge intent.

You could probably make it so crafting patterns end up in an interface next to a Molecular Assembler, but it might not be the right spot for it. Players often stripe their patterns across all interfaces in a MA multiblock as a load-balancing measure, or you might have multiple multiblocks around. The criteria for what is the "right" destination is highly subjective and routing logic rapidly becomes complex.

Then you have processing patterns, which are basically you telling AE2 to push some ingredients then a miracle happens and you'll get some other stuff back eventually. It has no way of knowing what the appropriate machine's interface is for something like that.

I agree it's a little annoying to have to manually place all the patterns, but that really does seem like the best option.

**Comment by Zenthae** [comment]
the best way to do it is to directly go to the interface instead of using the terminal, here you can shit click all you want
